services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.prod
      args:
        VITE_API_BASE_URL: /api/v1
    container_name: sopk_frontend
    expose:
      - "80"
    networks:
      - pk_proxy
    restart: unless-stopped

networks:
  pk_proxy:
    external: true
