// src/constants/permissions.js

export const PERMISSIONS = {
  SQUAD_VIEW_OWN: 'squad.view_own',
  SQUAD_MANAGE: 'squad.manage',

  MEMBERSHIP_JOIN_OWN: 'membership.join_own',
  MEMBERSHIP_MANAGE: 'membership.manage',

  AVAILABILITY_RESPOND_OWN: 'availability.respond_own',
  AVAILABILITY_MANAGE: 'availability.manage',

  FEE_VIEW_OWN: 'fee.view_own',
  FEE_MANAGE: 'fee.manage',

  ROSTER_VIEW_OWN: 'roster.view_own',
  ROSTER_VIEW_ALL: 'roster.view_all',
  ROSTER_MANAGE: 'roster.manage',
  ROSTER_PUBLISH: 'roster.publish',
}

export const ACCESS_GROUPS = {
  AVAILABILITY_PAGE: [
    PERMISSIONS.AVAILABILITY_RESPOND_OWN,
    PERMISSIONS.AVAILABILITY_MANAGE,
  ],

  MY_SCHEDULE_PAGE: [
    PERMISSIONS.ROSTER_VIEW_OWN,
    PERMISSIONS.ROSTER_VIEW_ALL,
    PERMISSIONS.ROSTER_MANAGE,
    PERMISSIONS.ROSTER_PUBLISH,
  ],

  MY_CHANGE_REQUESTS_PAGE: [
    PERMISSIONS.ROSTER_VIEW_OWN,
    PERMISSIONS.ROSTER_VIEW_ALL,
    PERMISSIONS.ROSTER_MANAGE,
  ],

  MY_SQUADS_PAGE: [
    PERMISSIONS.SQUAD_VIEW_OWN,
    PERMISSIONS.SQUAD_MANAGE,
    PERMISSIONS.MEMBERSHIP_JOIN_OWN,
    PERMISSIONS.MEMBERSHIP_MANAGE,
  ],

  MANAGE_AVAILABILITY: [
    PERMISSIONS.AVAILABILITY_MANAGE,
  ],

  MANAGE_SCHEDULES: [
    PERMISSIONS.ROSTER_MANAGE,
    PERMISSIONS.ROSTER_PUBLISH,
  ],

  MANAGE_CHANGE_REQUESTS: [
    PERMISSIONS.ROSTER_MANAGE,
  ],

  MANAGE_SCANNER: [
    PERMISSIONS.ROSTER_MANAGE,
  ],
}